version: "3"
services:
  seata-server:
    image: seataio/seata-server:${SEATA_VERSION}
    container_name: seata-server
    hostname: seata-server
    ports:
      - "8091:8091"
    environment:
      - SEATA_PORT=8091
      #- STORE_MODE=db
      - SEATA_IP=192.168.10.200
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
    volumes:
      - ./config:/root/seata-config
