apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: seata-ha-service
  labels:
    k8s-app: seata-ha-service
spec:
  type: NodePort
  ports:
    - port: 8104
      nodePort: 30084
      protocol: TCP
      name: http
  selector:
    k8s-app: seata-ha-service

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seata-ha-service-config
data:
  NACOS_ADDR: nacos-headless.default.svc.cluster.local:8848

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: seata-ha-account
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: seata-ha-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: seata-ha-account
    namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: seata-ha-service
  labels:
    k8s-app: seata-ha-service
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: seata-ha-service
  template:
    metadata:
      labels:
        k8s-app: seata-ha-service
    spec:
      serviceAccountName: seata-ha-account
      containers:
        - name: seata-ha-order-service
          image: solvaysphere/seata-ha-order-service:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: NACOS_ADDR
              valueFrom:
                configMapKeyRef:
                  key: NACOS_ADDR
                  name: seata-ha-service-config
          ports:
            - name: http
              containerPort: 8101
              protocol: TCP
        - name: seata-ha-account-service
          image: solvaysphere/seata-ha-account-service:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: NACOS_ADDR
              valueFrom:
                configMapKeyRef:
                  key: NACOS_ADDR
                  name: seata-ha-service-config
          ports:
            - name: http
              containerPort: 8102
              protocol: TCP
        - name: seata-ha-storage-service
          image: solvaysphere/seata-ha-storage-service:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: NACOS_ADDR
              valueFrom:
                configMapKeyRef:
                  key: NACOS_ADDR
                  name: seata-ha-service-config
          ports:
            - name: http
              containerPort: 8103
              protocol: TCP
        - name: seata-ha-business-service
          image: solvaysphere/seata-ha-business-service:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: NACOS_ADDR
              valueFrom:
                configMapKeyRef:
                  key: NACOS_ADDR
                  name: seata-ha-service-config
          ports:
            - name: http
              containerPort: 8104
              protocol: TCP
